const mongoose = require('mongoose')
//Everything in Mongoose starts with a Schema
//Each schema maps to a MongoDB collection and
//defines the shape of the documents within that collection
const Schema = mongoose.Schema

//define Schema 
const employeeSchema = new Schema(
    {
        //id is autogenerated here
        firstname: {
            type: String,
            required: true
        },
        lastname: {
            type: String,
            required: true
        }
    }
)

                                //create a data model here
                                //Employee is singular and will find its equivalent plural in the collections in mongoDB
module.exports = mongoose.model('Employee', employeeSchema)